apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: loja-veloz-devops-inventory-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: inventory-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secret
              key: DB_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        # Readiness: O serviço está pronto para receber tráfego?
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        # Liveness: O serviço travou e precisa ser reiniciado?
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15